### PR TITLE
Support Python 3.11 - Fix 447

### LINKED ISSUE #447: Gdbgui is not compatible with Python 3.11
**Describe the bug**

Gdbgui is not compatible with Python 3.11 because it requires `greenlet==1.1.2`.

See https://github.com/python-greenlet/greenlet/issues/295#issuecomment-1078891696 and https://github.com/python-greenlet/greenlet/pull/280.

**To Reproduce**

```
python3.11 -m pip install gdbgui 
```

**Please complete the following information:**
* OS: Archlinux
* gdbgui version (`gdbgui -v`): 0.15.1.0
* gdb version (`gdb -v`):
* browser [e.g. chrome, safari]:
* python packages (`pip freeze`):

**Additional context**

### PR DESCRIPTION
**Pull request by Cherrg**
### Support Python 3.11

- [x] I have added an entry to `CHANGELOG.md`, or an entry is not needed for this change
  - this should be done by the package maintainer, when a new version is released

- some of the problems are introduced by fixed requirements introduced in version 0.15.1.0
- build will run successfully with python3.11
  - tested on linux (`nox -s build_executables_current_platform`)
  - develop mode is working `nox -s develop`

## Summary of changes

- fix #447 
- this will bump some the versions of some requirements
- update the noxfile to support python 3.11
- fix the flake8 config file: comments should start in an extra line

## Test plan

Tested by running `nox`

```
nox > * tests-3.11: success
nox > * lint: failed
nox > * docs: success
nox > * cover: success
```

One of the linting errors is also handled with this PR. This change/PR has nothing to do with failed lint tests. They should be handled separately.
What failed?

- some datatypes - test by `mypy`
```
gdbgui/server/constants.py:14: error: Argument 1 to "Path" has incompatible type "Optional[Any]"; expected "Union[str, PathLike[str]]"  [arg-type]
gdbgui/server/sessionmanager.py:67: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
gdbgui/server/sessionmanager.py:103: error: Argument 1 to "IoManager" has incompatible type "FileIO"; expected "BufferedWriter"  [arg-type]
gdbgui/server/sessionmanager.py:104: error: Argument 2 to "IoManager" has incompatible type "FileIO"; expected "BufferedReader"  [arg-type]
```

- some missing dist files - test by `check-manifest`
```
lists of files in version control and sdist do not match!
missing from VCS:
  gdbgui/static/js/dashboard.js
  gdbgui/static/js/dashboard.js.map
  gdbgui/static/js/main.js
  gdbgui/static/js/main.js.map
```

### CODE REVIEW

**Comment by brandonros** [comment]
```
python3 -m pip install git+https://github.com/Cherrg/gdbgui.git@fix_447
```

http://127.0.0.1:5000/static/js/dashboard.js?_= 404s?

**Comment by jpihl** [comment]
It seems files in /static/js need to be generated. I don't know why this is not done when installing directly from Git.

I did the following **dirty hack** to get gdbgui working with python3.11 on Ubuntu 23.04:

```
pipx install git+https://github.com/Cherrg/gdbgui.git@fix_447
cd /tmp
git clone git+https://github.com/Cherrg/gdbgui.git@fix_447
cd gdbgui
npm install
npm run build
cp -r gdbgui/static/js ~/.local/pipx/venvs/gdbgui/lib/python3.11/site-packages/gdbgui/static
```

**Comment by enathang** [comment]
Hello! What is the status of the PR? 

Happy to jump in and help, but I don't see any issues tbh.

**Review by cs01 — APPROVED** [review]

**Comment by cs01** [comment]
Thank you!
