### ISSUE TITLE
flask fail with error 'Response' object has no attribute 'get_data'

### ISSUE THREAD

**Issue by abc19899** [cs01/gdbgui#153]
##### Describe the issue
flask fail
##### Steps to replicate

* gdbgui --gdb=/data/gdb-8.0.1/bin/gdb --port=8888 --host=0.0.0.0
* on browser nav to  http://XX.XX.XX.XX:8888/  (XX is the ip)
* got Internal Server Error 
* the console output is below:
Opening gdbgui in browser at http://127.0.0.1:8888
exit gdbgui by pressing CTRL+C
[2018-01-08 15:42:00,349] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 1632, in finalize_request
    response = self.process_response(response)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 1856, in process_response
    response = handler(response)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask_compress.py", line 97, in after_request
    gzip_content = self.compress(app, response)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask_compress.py", line 118, in compress
    gzip_file.write(response.get_data())
AttributeError: 'Response' object has no attribute 'get_data'

##### Describe your environment
* Operating system and version:
CentOS release 6.5 (Final)
Kernel \r on an \m
* gdbgui version (`gdbgui -v`):
0.9.4.1
* gdb version (`gdb -v`):
8.0.1
* browser:
chrome
* python packages (`pip freeze`):
Babel==0.9.6
certifi==2017.7.27.1
chardet==3.0.4
click==5.1
Cython==0.27.3
docutils==0.11
enum==0.4.6
Flask==0.12.2
Flask-Compress==1.4.0
Flask-SocketIO==2.9.3
future==0.16.0
gdbgui==0.9.4.1
gevent==1.2.2
greenlet==0.4.12
idna==2.5
itsdangerous==0.24
Jinja2==2.6
jsonpickle==0.9.5
MarkupSafe==0.11
nose==1.3.0
protobuf==3.3.0
pstack==0.6
pygdbmi==0.8.1.1
Pygments==2.2.0
python-engineio==2.0.2
python-socketio==1.8.4
requests==2.18.3
simplejson==3.2.0
six==1.10.0
snakeMQ==1.4
Sphinx==1.1.3
SQLAlchemy==0.7.9
urllib3==1.22
virtualenv==13.1.0
Werkzeug==0.8.3

**Comment by cs01** [comment]
Thanks for the report. I have confirmed this error given the environment you provided. 

If you upgrade Werkzeug to a later version it should fix it. I got it to work with `Werkzeug=0.14.1`.

Run `[sudo] pip install Flask -U` then try again.
